# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            咖喱屋
tagline:          '咖喱屋'
description:      '哈啰 我是一个自动驾驶算法工程师，希望在这里可以和志同道合的朋友分享更多的东西 :blush:'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           牛肉咖喱饭
  url:            https://twitter.com/peterjaq1

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/PeterJaq/PeterJaq.github.io
